CREATE DATABASE flipkarts;
use flipkarts;
SELECT*FROM mobiles;

-- DIFFERENT PRICE RANGE SEGMENTS FOR MOBILES IN INDIA 
SELECT Brand,
SUM(CASE WHEN MRP BETWEEN 0 AND 9999 THEN 1 ELSE 0 END) AS 'Price Below 10k',
SUM(CASE WHEN MRP BETWEEN 10000 AND 19999 THEN 1 ELSE 0 END) AS 'Price Below 10-20k',
SUM(CASE WHEN MRP BETWEEN 20000 AND 39999 THEN 1 ELSE 0 END) AS 'Price Below 20-40k',
SUM(CASE WHEN MRP >= 40000 THEN 1 ELSE 0 END) AS 'Price Below 40k'
FROM mobiles GROUP BY Brand ORDER BY Brand;

-- THE BRAND THAT HAS THE HIGHEST DISCOUNTED PRICE 
SELECT Brand, 
MAX(MRP-MSP) AS MaxDiscount
FROM mobiles GROUP BY Brand ORDER BY MaxDiscount DESC LIMIT 1;

-- TOP 5 BRANDS BY AVERAGE RATING 
SELECT Brand, AVG(RatingS) AS Avg_Rating FROM Mobiles GROUP BY Brand ORDER BY Avg_Rating DESC LIMIT 5;

-- TOP 5 BRANDS BY TOTAL NUMBER OF REVIEWS
SELECT Brand, SUM(No_Of_Reviews) AS Total_Reviews FROM Mobiles GROUP BY Brand ORDER BY Total_Reviews DESC LIMIT 5;

-- PRODUCTS WITH RATING GREATER THAN 4.5
SELECT*FROM mobiles WHERE Ratings >4.5;

-- PRODUCTS WITH DISCOUNTS GREATER THAN 40%
SELECT*FROM mobiles WHERE Discount >40;

-- AVGERAGE RATING & NUMBER OF REVIEWS PER BRAND 
SELECT Brand, AVG(Ratings)AS Avg_Rating, SUM(No_Of_Reviews) AS Total_Reviews FROM mobiles GROUP BY Brand ORDER BY Avg_Rating DESC;

-- PRODUCTS WITH THE HIGHEST DISCOUNTS 
SELECT*FROM Mobiles ORDER BY Discount DESC LIMIT 5;

-- GET UNIQUE BRAND NAMES
SELECT DISTINCT Brand FROM Mobiles;

